### ISSUE TITLE
Build failed ...

### ISSUE THREAD

**Issue by mustakimur** [bananaappletw/symgdb#1]
Hi
I was trying to build the symgdb, but it failed. It seems the reason is the Triton source is not as expected as you use. 
src/libtriton/CMakeFiles/gen-syscall64.dir/build.make:61: recipe for target 'src/libtriton/os/unix/syscalls64.cpp' failed
I didn't find this syscalls64.cpp instead have found syscallNumberToString.cpp there in latest version.

**Comment by bananaappletw** [comment]
@mustakcsecuet 
Maybe remove the whole project(Triton) and try again?
It seems like you have executed `cmake` command before, then you upgrade the Triton source code and `make`.
Thank you.

**Comment by bananaappletw** [comment]
@mustakcsecuet Do you succeed?

**Comment by bananaappletw** [comment]
@mustakcsecuet I just upgrade to Triton 0.6, maybe you could try again.
